services:
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/dockerfile
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_root_password
      - db_password 
    volumes:
      - mariadb_data:/var/lib/mysql 
    networks:
      - inception_network
    expose:
      - 3306
  wordpress:
    